# helmfile.yaml
repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

apiVersions:
  - monitoring.coreos.com/v1

releases:
- name: ingress
  chart: ./ingress
- name: argocd
  namespace: argocd
  chart: argo/argo-cd
  values:
  - global:
      domain: argocd.local.amazinglyabstract.it
    server:
      ingress:
        enabled: true
    configs:
      params:
        "server.insecure": true
- name: kargo
  namespace: kargo
  createNamespace: true
  chart: oci://ghcr.io/akuity/kargo-charts/kargo
  version: 1.4.4
  values:
  - api:
      host: kargo.local.amazinglyabstract.it
      ingress:
        enabled: true
        tls:
          enabled: false
      tls:
        enabled: false
  set:
  - name: api.adminAccount.passwordHash
    value: "$2y$10$RZtCHiQbYjJ3N22P0qvxLOQuxPgYhO7dooSnKB.vq95auK4fLn0fS"
  - name: api.adminAccount.tokenSigningKey
    value: "rsQGhNEeGEpuBf9dwOjLD1xCRNeHXSKL"
- name: argo-rollouts
  namespace: argocd
  chart: argo/argo-rollouts
  values:
- name: kargo-config
  chart: ./kargo
  createNamespace: true
- name: argocd-config
  chart: ./argocd
