apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: guestbook-prod-central

patches:
  - target:
      kind: Ingress
      name: guestbook
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: guestbook-prod-central.local.amazinglyabstract.it
